repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        args: ["--config-file=.config/mypy.ini"]
        description: "Type checker"
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ["--config=.config/.flake8"]
        description: "Your Tool For Style Guide Enforcement"
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args:
          - --config=.config/.pydocstyle
        description: "Doc strings checker"
  - repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
        args:
          [
            "--rcfile=.config/.pylintrc",
            "--ignore-paths=^(tests/.*$|py_zippin/db/orm/.*$|py_zippin/store_redis/.*$|docs/.*$)",
          ]
